### ISSUE TITLE
List class

### ISSUE THREAD

**Issue by scriptingstudio** [santisq/PSParallelPipeline#10]
`System.Collections.Generic.List<T>` does not have a property `Instance`
```powershell
$tasks = [System.Collections.Generic.List[hashtable]]::new()
$tasks.add(@{v=44})
$tasks.Instance.dispose()
You cannot call a method on a null-valued expression.
At line:1 char:1
+ $tasks.Instance.dispose()
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```
https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1?view=net-7.0#properties

**Comment by santisq** [comment]
@scriptingstudio  I'm not sure what is this issue about? Please share more details.

**Comment by scriptingstudio** [comment]
it is about that `$tasks.Instance.dispose()` is nonsense

**Comment by scriptingstudio** [comment]
expression `$tasks.Instance | ForEach -MemberName dispose` hides errors because `foreach-object` skips nul elements

**Comment by santisq** [comment]
@scriptingstudio Not sure what are you talking about:

```powershell
$tasks = [System.Collections.Generic.List[hashtable]]::new()
0..10 | ForEach-Object {
    $tasks.Add(@{ Instance = [powershell]::Create() })
}
$tasks.Instance.Dispose()
```

Please read the code in detail before submitting nonsensical issues.
