### ISSUE TITLE
Task finishing

### ISSUE THREAD

**Issue by scriptingstudio** [santisq/PSParallelPipeline#9]
In this implementation task finishing is not asynchronous because `.EndInvoke` method waits for the delegate to finish executing. So they end in sequence. 
You should check `$task['AsyncResult'].IsCompleted` flag. 
And, yes, in this case `TimeoutSeconds` would be useful.

**Comment by santisq** [comment]
@scriptingstudio this makes a good point. `TimeoutSeconds` will be implemented in future Release.

**Comment by santisq** [comment]
@scriptingstudio thanks for raising the issue. New version should do both.
